---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# maxnetmap

The goal of maxnetmap is to create a 
raster from a spatial distribution model fitted with glmnet via maxnet 
package

## Installation

You can install maxnetmap from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("alrobles/maxnetmap")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
## basic example code
library(spocc)
library(raster)

# get enviromental variables
currentEnv <- raster::getData("worldclim", var="bio", res=2.5)
#set an extent
model_extent <- raster::extent(-130,-60,25,50) 

#crop the enviromental layers
modelEnv <- raster::crop(currentEnv, model_extent)
#get the points of rice
pts <- spocc::occ("Oryza sativa", geometry = as.vector(model_extent) ) %>% 
    spocc::occ2df() %>% 
    dframe() %>% 
    coord_impossible() %>%
    coord_incomplete() %>%
    coord_unlikely()

#plot a layer with the points
plot(modelEnv[[1]])
points(pts[ ,2:3],col="red", pch=20, cex=0.3)

# get a maxent model with the raster
me <- maxentRaster(modelEnv, pts[ ,2:3], fclasses)

#raster
plot(me[[1]])

#model
plot(me[[2]])
me[[2]]$nulldev

```
